- .travis.yml
- client/nginx.conf
- docker-compose.yml
- docker/client.Dockerfile
- docker/server.Dockerfile
- server/.babelrc
- server/.eslintignore
- server/.gitignore
- server/app.js
- server/bin/util.js
- server/bin/www
- server/package-lock.json
- server/package.json
- server/routes/index.js
- server/webpack.config.js
객체 설계 후 나온 디렉토리 구조대로 server 디렉토리를 구성했습니다.
ES module 사용을 위해 webpack, babel 설정했습니다.
server에서도 eslint, prettier 설정했습니다.
docker compose 사용을 위해 dockerfile 추가했습니다.
travis.yml 추가했습니다.
> [feature/ci] 0-6

- client/package-lock.json
- client/package.json
- client/src/index.js
- server/app.js
- server/bin/www
- server/package-lock.json
- server/package.json
react client랑 express server socket 연결했습니다.
> [Feature/socket.io] 6-1,2

- server/package.json
package.json 에 devDependencies가 두 개가 생겨 수정함.
> package.json 오류 수정

- .travis.yml
- docker-compose.yml
- docker/mysql.Dockerfile
- mysql/initdb.sql
- mysql/utf8.cnf
- script/deploy.sh
- script/docker-compose.yml
- server/.gitignore
-  mysql docker 환경 마련
-  초기 데이터 넣어주는 .sql 작성
-> mysql.Dockerfile 추가
-> docker-compose에서 mysql.Dockerfile 실행하도록 함
-  패스워드 암호화를 해결해야함
> [feature/db] 11-1

- client/src/class/socket.js
- client/src/component/Room/GameArea/Field.js
- client/src/constants/socket-event.js
socket class 구현 후 내부에서 connect하게 구현
> [feature/socket] client에서 socket 연결 구현

- client/package-lock.json
- client/package.json
- client/src/class/socket.js
- client/src/component/Room/GameArea/Field.js
- client/src/index.js
- client/src/reducer/index.js
- client/src/store/index.js
react, react-redux 사용
store, reducer, action 초기 폴더 및 파일 생성
필요한 reducer ,action을 정의 후 컴포넌트에서는 useSelector, useDispatch를 사용해서 state를 변경하는 구조입니다.
> [feature/redux] react에 redux 적용

- client/src/reducer/index.js
렌더링 되기전에 에러 발생으로, 초기 reducer를 생성해주는 코드 추가
> [feature/redux] root reducer에 초기 reducer가 없는 문제 수정

- mysql/initdb.sql
-  필요한 테이블 추가
-  Image
-  초기 데이터베이스 추가
-  background / character / logo 등
> image table 추가, 초기 데이터베이스 추가

- client/public/index.html
- client/src/component/Room/GameArea/DashBoard.js
- client/src/component/Room/GameArea/style.js
styled component 이용하여 전광판 화면 css 구성함.
추가로 setTimeout 이용하여, 시간 카운트 기능 구현함.
> [feature/dashboard] 8-2

- server/app.js
- server/controllers/index.js
- server/database/connection.js
- server/database/quiz.js
- server/models/quiz.js
- server/models/room.js
- server/package-lock.json
- server/package.json
-  컨트롤러, quiz 모델, room 모델 구현
-  현재는 방이 1개인 상태라 방에 있는 플레이어들에게 전달하지 않음
-  접속한 모든 플레이어에게 문제를 전달하고 있음
> [feature/startgame] 11-3 

- .travis.yml
- client/src/component/Room/GameArea/DashBoard.js
- client/src/component/Room/GameArea/style.js
- client/src/component/Room/index.js
- client/src/component/Room/style.js
- client/src/constants/room.js
- client/src/index.css
전광판 게임 진행 상태, 플레이어의 방장 여부 따라 전광판 다르게 보이도록 구현하였습니다.
> [feature/dashboard] 8-2, 3

- server/models/player.js
- server/models/room.js
- server/models/player.js와 room.js 에 jsdoc 예시 주석 추가
- 예시로. 참고하기 위함
- develop branch와 똑같도록 getRandomCharacter에서 get을 fetch로 수정
> Jsdoc 예시 주석 추가 (#77)

- server/controller/index.js
- server/models/character.js
- server/models/room.js
- server/models/user.js
기존 User model에서 character를 할당하는 것은 잘못되었다고 생각되기에,
controller에서 방 입장 시 character 할당하도록 변경함.
> 캐릭터를 Controller에서 유저에게 할당하도록 변경

- client/src/class/socket.js
- client/src/component/Room/GameArea/Field.js
- client/src/component/Room/index.js
- client/src/constants/socket-event.js
- server/app.js
- server/constants/room.js
- server/constants/socket-event.js
- server/controller/index.js
- server/models/character.js
- server/models/lobby.js
- server/models/room.js
- server/models/user.js
- lobby 클래스를 추가해서 구조 잡음
- 현재는 임시로 test room을 만들어 놓고, 서버에서 socket 연결이 되면 방 정보 리스트를 보내고 test room으로 입장시킴
- room 에 입장하면 캐릭터가 표시될 수 있게 돌아가는 코드 구현
> [feature/lobby model] 서버 모델에 lobby 개념 추가, 클라이언트를 서버 emit에 대응할 수 있게 수정

- client/src/class/character.js
nickname그리는 위치가 잘못되어서 fixg하였어요.
모두 제 잘못입니다. 더 욕하셔도 돼요 ^-^
> nickname을 그리는 위치 수정

- client/src/class/socket.js
- client/src/component/Room/GameArea/DashBoard.js
- client/src/constants/room.js
- server/constants/room.js
- server/models/room.js
- 13 : 제한시간이 끝나면 답이 공개된다.
- 13-1 : 서버가 시작 명령을 보내고, 클라이언트는 시간을 표시한다.
- 13-2 : 제한시간이 끝나면 전광판에 O/X가 표시된다.
- 19 : 게임이 종료되면 방이 대기상태로 돌아간다.
- 19-1 : 전광판의 표시를 바꾼다.
-  아래 task가 반영된 develop branch를 merge한 후 push 했습니다.
- 14 : 오답 진영의 플레이어들은 탈락하고 관전자가 된다.
- 14-1 : 탈락한 클라이언트들의 캐릭터는 사라지고, 게임에 참여할 수 없다.
> [feature/time] 13-1, 13-2, 19-1

- server/models/room.js
-  같은 방에서 재시작하는 경우를 위해서
-  endGame broadcast를 해주는 함수를 따로 만듦
> 룸 모델이 게임을 시작할 때 현재 유저수를 반영하도록함

- client/src/class/socket.js
- client/src/component/Room/GameArea/DashBoard.js
- server/constants/room.js
- server/models/room.js
- server/models/user.js
- game start시 라운드 시작 전에 이벤트를 하나 더 만들어서 클라이언트에서 3초 카운트하면 라운드가 시작되게 했습니다. 게임의 재미를 위해^_^
> [feature/game ready] 게임 시작 시 3초 카운트 후 시작되는 기능 구현

- client/src/component/Room/GameArea/DashBoard.js
- server/models/room.js
방장 여부에 따라 전광판 다르게 보여서, 방장만 시작 가능함.
또한 방장이 나간 경우, 새로운 방장인 유저에게 시작 가능하도록 구현함.
> [feature/room-owner] 8-4

- client/src/component/Room/GameArea/DashBoard.js
- client/src/component/Room/GameArea/style.js
- server/models/room.js
-  [18-1] 게임이 종료되면 우승자가 표시된다., 전광판에 우승자의 닉네임을 표시한다.
-  우승자 닉네임 대신 살아남은 플레이어 모두에게 우승표시하도록함
-  카운터도 없애주고 가운데 정렬하도록함
> [feature/winner] 18-1 게임이 종료되면 우승자가 표시된다.

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/component/Lobby/index.js
- client/src/component/Lobby/style.js
- client/src/component/Room/GameArea/style.js
- client/src/component/Room/index.js
- client/src/index.css
다양한 페이지를 구현하기 위해, react-router 도입 및 반영함.
추가로 lobby page 스타일 작업함.
이 때, 전체 page에 대한 기본 font를 retro함을 주기 위해 둥근모꼴로 변경 및 반영함.
> [feature/lobby-page] 4-0

- client/src/component/Room/GameArea/DashBoard.js
- client/src/constants/room.js
-  리액트 컴포넌트가 unmount될 때 마지막 setTimeout을 클리어 하도록
-  상수화 되지 않은 값을 상수화
-  지나치게 길었던 컴포넌트 이름을 바꿈
> 코드리뷰 받은 내용을 바탕으로 리팩토링

- client/nginx.conf
- client/src/App.js
- client/src/class/socket.js
- client/src/component/Lobby/GitHubLoginButton/index.js
- client/src/component/Lobby/GitHubLoginButton/style.js
- client/src/component/Lobby/RoomCreateModal/index.js
- client/src/component/Lobby/RoomCreateModal/style.js
- client/src/component/Lobby/RoomInfoButton/index.js
- client/src/component/Lobby/RoomInfoButton/style.js
- client/src/component/Lobby/index.js
- client/src/component/Lobby/style.js
- client/src/component/Room/GameArea/Field.js
- client/src/component/Room/index.js
- client/src/constants/lobby.js
- client/src/constants/modal.js
- client/src/constants/room.js
- client/src/constants/socket-event.js
- mysql/initdb.sql
- server/constants/socket-event.js
- server/controller/index.js
- server/models/lobby.js
- server/models/user.js
- server/package.json
- server/util/index.js
- react-router 도입 후 nginx 라우팅과 충돌되는 문제 해결
- room으로 들어왔을 때 파라미터 이름을 roomId로 변경
- 로비 페이지, 방 생성 모달 UI 및 생성 후 자동 입장 기능 구현
> [feature/lobby-modal] 4-1, 4-2

- server/app.js
- server/database/image.js
- server/database/nickname.js
- server/database/quiz.js
- server/database/user.js
- server/middlewares/isAdmin.js
- server/package-lock.json
- server/package.json
- server/routes/admin/image.js
- server/routes/admin/index.js
- server/routes/admin/nickname-adj.js
- server/routes/admin/nickname-noun.js
- server/routes/admin/quiz.js
- server/routes/admin/user.js
- server/util/index.js
user, nickname, quiz, image 테이블의 CRUD 기능을 관리자페이지로 실행하기 위해, API 구현함.
로컬에서 개발할 경우, 요청 경로의 시작은 /admin 이어야 하며,
실제 서버에 배포될 때는, 요청 경로의 시작이 /api/admin 이어야 한다.
관련 이슈: #118, #120, #121, #125, #127, #137, #138, #139, #140
> [feature/admin-api] 1-1, 1-2, 1-3, 1-4, 2-1, 2-2, 2-3, 2-4, 2-5

- client/src/components/Lobby/RoomInfoButton/index.js
- client/src/components/Lobby/index.js
- client/src/components/Login/index.js
- client/src/components/Room/ChatArea/Info.js
- client/src/components/Room/ChatArea/Input.js
- client/src/components/Room/index.js
- client/src/modules/socket.js
- server/controller/index.js
- server/models/room.js
- server/models/user.js
- '뒤로가기' 클릭 시 history가 엉키는 문제가 있어 push 대신 replace로 임시적으로 대치
- 인원이 1명이라서 게임 시작할 수 없는데, 로비에는 시작되었다고 반영되는 버그 수정
- 채팅창에 제한길이 초과해서 보낼 수 있는 버그 수정
- client socket 모듈의 중복되는 코드 개선
- react fragment 사용
추가사항
- 형규님 코드리뷰 반영함.
> 지난 금요일 버그데이를 위한 코드 수정 반영(2)

- docker-compose.yml
-  docker-compose에서 volume을 이용해 데이터 보존
-  admin 페이지에서 수정한 사항들이 반영되고 새로운 배포 후에도 유지도되도록 하기 위해
-  수정한 파일은 local에서 docker-compose 사용시에만 영향을 끼친다. 참고용입니다.
-  https://github.com/connect-foundation/2019-01/issues/71
-  https://github.com/connect-foundation/2019-01/issues/193
-  https://github.com/connect-foundation/2019-01/issues/196
> docker mysql 데이터 보존

- client/src/components/Lobby/GitHubLoginButton/style.js
- client/src/components/Lobby/RoomCreateModal/style.js
- client/src/components/Lobby/RoomInfoButton/style.js
- client/src/components/Lobby/index.js
- client/src/components/Lobby/style.js
- client/src/components/Login/style.js
- client/src/components/Room/ChatArea/RoomName/style.js
- client/src/components/Room/ChatArea/style.js
- client/src/components/Room/GameArea/DashBoard.js
- client/src/components/Room/GameArea/index.js
- client/src/components/Room/GameArea/style.js
- client/src/components/Room/index.js
- client/src/components/Room/style.js
- client/src/constants/lobby.js
- client/src/constants/modal.js
- client/src/constants/room.js
- client/src/constants/url.js
- room 페이지에서 배경음악이 자동 재생되도록 구현했습니다.
- game start 버튼을 클릭할 때 효과음이 재생되도록 구현했습니다.
- game start 시 효과음, end 시에도 효과음이 재생되도록 구현했습니다.
- room 페이지 우측 상단의 sound toggle을 사용해서 사용자가 소리를 끄고 켤 수 있도록 구현했습니다.
- new Audio를 사용해 audio element를 생성하고, autoplay, loop, pause, muted, onended 프로퍼티를 사용해서 제어했습니다.
> [feature/sound] 21-2

- client/src/components/Lobby/index.js
- github 로그인한 유저가 lobby -> room -> lobby로 돌아온 경우, lobby에 guest로 나오는 버그 해결하였습니다.
너무 간단해서 깜짝...!
> [bugfix/guest] 31-5 

- client/src/components/Room/ChatArea/Input.js
- 채팅창에서 input box에 아무 내용이 없고, enter 키를 눌렀을 경우 focus 를 out 시켜서 바로 캐릭터를 움직일 수있게 했습니다.
> [feature/input focus] 31-3

- client/src/components/Room/GameArea/Field.js
- client/src/constants/socket-event.js
- client/src/modules/socket.js
- server/constants/socket-event.js
- server/controller/index.js
- server/models/room.js
- server/models/user.js
스킬 사용 방법: 사용하고자 하는 상대 캐릭터 바로 옆에서 shift 키 + 날릴 방향을 같이 누르면 스킬 발동됨
단, 스킬 사용에 대한 제약(한 라운드에 한번만 가능 등)은 아직 없음
사실 게임 개판으로 되면 재밌을 것 같아 제약이 없으면 어떨까 싶기도 함..ㅋ
> 유저 스킬(리신 궁) 및 서버 내부의 moveQueue 구현

- client/nginx.conf
- client/src/modules/socket.js
- docker-compose.yml
- docker/client.Dockerfile
> [feature/travis] 0-16

- client/src/components/Room/ChatArea/Info.js
- client/src/constants/socket-event.js
- client/src/modules/socket.js
- server/constants/socket-event.js
- server/models/room.js
- server/models/user.js
- 기존 방식: 플레이어 수가 변하는 타이밍마다 클라이언트에서 직접 계산 후 적용.
- 바뀐 방식: 플레이어 수가 변하는 타이밍마다 서버에서 계산 후 별도의 이벤트로 클라이언트에게 알림.
> [bugfix/player number] 31-9

- client/src/components/Room/ChatArea/Info.js
- client/src/components/Room/GameArea/DashBoard.js
- client/src/components/Room/GameArea/Field.js
- client/src/components/Room/index.js
- client/src/constants/socket-event.js
- client/src/modules/socket.js
- server/constants/socket-event.js
- server/controller/index.js
- server/models/room.js
- server/models/user.js
- client와 server의 캐릭터 위치 리셋 싱크가 안맞던 부분을 resetGame이라는 event를 추가하여 fix하였습니다.
> [bugfix/character] 36-2

- client/src/components/Room/GameArea/Field.js
- client/src/modules/character.js
- server/models/room.js
리신 궁하는 도중 텔레포트를 시키면 남은 moveQueue에 있는 move를 나중에 실행시키면서 버그가 발생했습니다.
버그 fix하기 위해 텔레포트시킬 때 server와 client 모두 moveQueue를 비워줬습니다.
> [bugfix/character] 36-2 추가

- client/src/components/Lobby/index.js
- client/src/components/Login/index.js
- client/src/modules/socket.js
한번 github로 로그인하면 jwt cookie가 남아있어서 익명으로 로그인하기 버튼을 눌러도 github user로 로그인되던 부분 fix하였습니다.
> [bugfix/login] 36-5

- client/src/components/Room/ChatArea/Input.js
- client/src/components/Room/ChatArea/style.js
- client/src/constants/room.js
- client/src/modules/character.js
- client/src/util/index.js
- parseChat을 util로 뺌
- 채팅창에서도 길이를 검사하기 위해서 길이검사용 canvas를 생성하여 이용함
- 관련 이슈 : #226, #246
> [bugfix/chatting] 36-4

- client/src/components/Admin/ImageCategory/ImageModal/Row.js
- client/src/components/Admin/ImageCategory/ImageModal/index.js
- client/src/components/Admin/ImageCategory/ImageModal/style.js
- client/src/components/Admin/ImageCategory/Row.js
- client/src/components/Admin/ImageCategory/index.js
- client/src/components/Admin/ImageCategory/style.js
- client/src/components/Admin/QuizCategory/QuizModal/index.js
- client/src/components/Admin/QuizCategory/index.js
- client/src/components/Admin/index.js
- client/src/constants/url.js
- server/database/image.js
- server/routes/admin/image.js
admin 페이지에 image catrgory를 추가하여 image를 추가,삭제,수정할 수 있는 기능을 구현하였습니다.
> [feature/admin] 41-1

- client/src/components/Admin/QuizCategory/QuizModal/index.js
> [bugfix/build] 오타로 인한 빌드 오류 해결

- client/src/App.js
- client/src/components/Alert/index.js
- client/src/components/Alert/style.js
- client/src/components/Lobby/index.js
- client/src/components/Login/index.js
- client/src/components/OAuth/index.js
- client/src/components/OAuth/popupGitHubOAuth.js
- client/src/components/Room/ChatArea/Info.js
- client/src/components/Room/GameArea/DashBoard.js
- client/src/components/Room/index.js
- client/src/constants/oauth.js
- client/src/constants/socket-event.js
- client/src/modules/socket.js
- client/src/util/index.js
- server/app.js
- server/constants/socket-event.js
- server/controller/index.js
- server/models/room.js
- server/models/user.js
- history replace -> push 변경
- 없는 방에 들어간 경우에 대한 에러처리 반영
- util성 함수 분리
- dotenv 설정 App.js로 이동
- Alert 컴포넌트 room 하위에 있던 것 상단으로 이동
- 코드리뷰 반영 (불필요한 라인 삭제 / 창 확인 간격 변경)
관련이슈: #210
> [bugfix/history-oauth] 

- server/app.js
- server/controller/index.js
- server/models/lobby.js
- server/models/room.js
- server/models/user.js
코드 품질 향상을 위한 리팩토링 진행
- 코드 순서 변경
- 함수 이름 전체 스타일에 맞게 변경
- 서버의 user 모델에서도 공통의 _on, _emit 메서드 추가 및 반영
> [refactor/server-controller-lobby] 37-1

- client/nginx.conf
- client/src/components/Admin/NicknameCategory/Nickname.js
- client/src/components/Admin/NicknameCategory/Row.js
- client/src/constants/url.js
- server/constants/error-message.js
- server/constants/lobby.js
- server/controller/index.js
- server/database/image.js
- server/database/nickname.js
- server/database/quiz.js
- server/database/user.js
- server/middlewares/login.js
- server/middlewares/logout.js
- server/models/lobby.js
- server/routes/admin/image.js
- server/routes/admin/quiz.js
- server/routes/admin/user.js
- server/routes/lobby.js
- server/util/index.js
- query 문 보기 쉽게 줄바꿈
- query 호출 메서드 통일성 있게 변경(ex. `updateImage` -> `update`)
- axios 호출 방식 통일화
- 불필요한 코드 삭제(middlewares/logout.js)
- 오타(`ADMIN.ADMINSNACKBAR_TIME_MS` -> `ADMIN.SNACKBAR_TIME_MS`) 수정
- 상수 중 닉네임 URL만 뒤에 `/`가 붙어있어 이를 수정
> [refactor/server-api]

- LICENSE.md
- client/package.json
- server/package.json
서버, 클라이언트 package.json versioning
MIT License 표시할 수 있도록 파일 추가
> versioning 및 license 파일 추가

- client/src/components/Login/index.js
- client/src/components/Login/style.js
- client/src/components/Style/Login.js
- client/src/constants/login.js
기존 로그인 배경이미지를 제거하고 서비스 로고를 이미지 tag로 추가하여 login 페이지를 변경함
> Login page UI 수정

- script/docker-compose.yml
- server/app.js
- server/constants/url.js
- server/package.json
- server/routes/index.js
- server/test/client.js
- server/test/mock.js
- server/test/socket-server.test.js
- move, chat, game event 에 대한 event 추가
- index router 설정
- cors 버그 수정
> [test/socket] socket event test 추가

- client/src/components/Room/index.js
- client/src/components/Room/style.js
- client/src/components/Style/Room.js
크리스마스 + 데모데이를 위해 방 배경에 눈 내리는 효과를 적용함.
적용한 방법은 gif를 이용함.
- gif 출처: https://giphy.com/stickers/transparent-gfllffmJEBXju33FPg
> 방 배경에 눈 내리는 효과 적용
